# Generated by Django 4.0.1 on 2022-01-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alternativa',
            fields=[
                ('id_alternativa', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('correcta', models.BigIntegerField()),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alternativa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id_comentario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mensaje', models.CharField(max_length=200)),
                ('puntuacion', models.BigIntegerField()),
                ('foto_solucion', models.BinaryField()),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_curso', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id_examen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=120, null=True)),
                ('numero_preguntas', models.BigIntegerField(blank=True, null=True)),
                ('puntaje_requerido', models.BigIntegerField()),
                ('duracion', models.BigIntegerField()),
            ],
            options={
                'db_table': 'examen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id_publicacion', models.BigIntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'publicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipopregunta',
            fields=[
                ('id_tipo_pregunta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'tipopregunta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('apellido', models.CharField(max_length=250)),
                ('correo', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarioexamen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarioexamen',
                'managed': False,
            },
        ),
    ]
